version: "3.8"

services:
  all-bots:
    image: bash
    restart: "no"
    depends_on:
      - busybot-1
      - busybot-2
      - busybot-3

  busybot-1:
    image: busybot:local
    build:
      context: .
      dockerfile: ./dockerbuild/busybot_build
    restart: always
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
      REST_URL_BASE: ${REST_URL_BASE}
      WEBSOCKET_URL: ${WEBSOCKET_URL}
      VERIFY_SSL: ${VERIFY_SSL:-true}
      ASSET_FILTER: ${ASSET_FILTER:-}
      API_KEY: ${BOT_1_API_KEY}
      API_SECRET: ${BOT_1_API_SECRET}
      ACTION_INTERVAL: ${BOT_1_ACTION_INTERVAL:-10000}
      CHANCE_CREATE_RFQ: ${BOT_1_CHANCE_CREATE_RFQ:-0.25}
      CHANCE_MODIFY_RFQ: ${BOT_1_CHANCE_MODIFY_RFQ:-0.25}
      CHANCE_CREATE_OFFER: ${BOT_1_CHANCE_CREATE_OFFER:-0.25}
      CHANCE_MODIFY_OFFER: ${BOT_1_CHANCE_MODIFY_OFFER:-0.25}
      CHANGE_ANSWER_OFFER: ${BOT_1_CHANGE_ANSWER_OFFER:-0.25}
      CHANCE_CREATE_COUNTER: ${BOT_1_CHANCE_CREATE_COUNTER:-0.25}
      CHANCE_MODIFY_COUNTER: ${BOT_1_CHANCE_MODIFY_COUNTER:-0.25}
      CHANGE_ANSWER_COUNTER: ${BOT_1_CHANGE_ANSWER_COUNTER:-0.25}
      CHANCE_MODIFY_RFQ_UPDATE: ${BOT_1_CHANCE_MODIFY_RFQ_UPDATE:-0.5}
      CHANCE_MODIFY_OFFER_UPDATE: ${BOT_1_CHANCE_MODIFY_OFFER_UPDATE:-0.5}
      CHANCE_MODIFY_COUNTER_UPDATE: ${BOT_1_CHANCE_MODIFY_COUNTER_UPDATE:-0.5}
      CHANCE_ANSWER_OFFER_ACCEPT: ${BOT_1_CHANCE_ANSWER_OFFER_ACCEPT:-0.5}
      CHANCE_ANSWER_COUNTER_ACCEPT: ${BOT_1_CHANCE_ANSWER_COUNTER_ACCEPT:-0.5}
    volumes:
      - ${BUSYBOT_LOG_ROOT}/busybot1:/var/log/busybot

  busybot-2:
    image: busybot:local
    build:
      context: .
      dockerfile: ./dockerbuild/busybot_build
    restart: always
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
      REST_URL_BASE: ${REST_URL_BASE}
      WEBSOCKET_URL: ${WEBSOCKET_URL}
      VERIFY_SSL: ${VERIFY_SSL:-true}
      ASSET_FILTER: ${ASSET_FILTER:-}
      API_KEY: ${BOT_2_API_KEY}
      API_SECRET: ${BOT_2_API_SECRET}
      ACTION_INTERVAL: ${BOT_2_ACTION_INTERVAL:-10000}
      CHANCE_CREATE_RFQ: ${BOT_2_CHANCE_CREATE_RFQ:-0.25}
      CHANCE_MODIFY_RFQ: ${BOT_2_CHANCE_MODIFY_RFQ:-0.25}
      CHANCE_CREATE_OFFER: ${BOT_2_CHANCE_CREATE_OFFER:-0.25}
      CHANCE_MODIFY_OFFER: ${BOT_2_CHANCE_MODIFY_OFFER:-0.25}
      CHANGE_ANSWER_OFFER: ${BOT_2_CHANGE_ANSWER_OFFER:-0.25}
      CHANCE_CREATE_COUNTER: ${BOT_2_CHANCE_CREATE_COUNTER:-0.25}
      CHANCE_MODIFY_COUNTER: ${BOT_2_CHANCE_MODIFY_COUNTER:-0.25}
      CHANGE_ANSWER_COUNTER: ${BOT_2_CHANGE_ANSWER_COUNTER:-0.25}
      CHANCE_MODIFY_RFQ_UPDATE: ${BOT_2_CHANCE_MODIFY_RFQ_UPDATE:-0.5}
      CHANCE_MODIFY_OFFER_UPDATE: ${BOT_2_CHANCE_MODIFY_OFFER_UPDATE:-0.5}
      CHANCE_MODIFY_COUNTER_UPDATE: ${BOT_2_CHANCE_MODIFY_COUNTER_UPDATE:-0.5}
      CHANCE_ANSWER_OFFER_ACCEPT: ${BOT_2_CHANCE_ANSWER_OFFER_ACCEPT:-0.5}
      CHANCE_ANSWER_COUNTER_ACCEPT: ${BOT_2_CHANCE_ANSWER_COUNTER_ACCEPT:-0.5}
    volumes:
      - ${BUSYBOT_LOG_ROOT}/busybot2:/var/log/busybot

  busybot-3:
    image: busybot:local
    build:
      context: .
      dockerfile: ./dockerbuild/busybot_build
    restart: always
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
      REST_URL_BASE: ${REST_URL_BASE}
      WEBSOCKET_URL: ${WEBSOCKET_URL}
      VERIFY_SSL: ${VERIFY_SSL:-true}
      ASSET_FILTER: ${ASSET_FILTER:-}
      API_KEY: ${BOT_3_API_KEY}
      API_SECRET: ${BOT_3_API_SECRET}
      ACTION_INTERVAL: ${BOT_3_ACTION_INTERVAL:-10000}
      CHANCE_CREATE_RFQ: ${BOT_3_CHANCE_CREATE_RFQ:-0.25}
      CHANCE_MODIFY_RFQ: ${BOT_3_CHANCE_MODIFY_RFQ:-0.25}
      CHANCE_CREATE_OFFER: ${BOT_3_CHANCE_CREATE_OFFER:-0.25}
      CHANCE_MODIFY_OFFER: ${BOT_3_CHANCE_MODIFY_OFFER:-0.25}
      CHANGE_ANSWER_OFFER: ${BOT_3_CHANGE_ANSWER_OFFER:-0.25}
      CHANCE_CREATE_COUNTER: ${BOT_3_CHANCE_CREATE_COUNTER:-0.25}
      CHANCE_MODIFY_COUNTER: ${BOT_3_CHANCE_MODIFY_COUNTER:-0.25}
      CHANGE_ANSWER_COUNTER: ${BOT_3_CHANGE_ANSWER_COUNTER:-0.25}
      CHANCE_MODIFY_RFQ_UPDATE: ${BOT_3_CHANCE_MODIFY_RFQ_UPDATE:-0.5}
      CHANCE_MODIFY_OFFER_UPDATE: ${BOT_3_CHANCE_MODIFY_OFFER_UPDATE:-0.5}
      CHANCE_MODIFY_COUNTER_UPDATE: ${BOT_3_CHANCE_MODIFY_COUNTER_UPDATE:-0.5}
      CHANCE_ANSWER_OFFER_ACCEPT: ${BOT_3_CHANCE_ANSWER_OFFER_ACCEPT:-0.5}
      CHANCE_ANSWER_COUNTER_ACCEPT: ${BOT_3_CHANCE_ANSWER_COUNTER_ACCEPT:-0.5}
    volumes:
      - ${BUSYBOT_LOG_ROOT}/busybot3:/var/log/busybot
