version: "3.8"

services:
  busybot:
    image: busybot:local
    build:
      context: ../
      dockerfile: ./docker/busybot_build
    container_name: busybot
    restart: always
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
      REST_URL_BASE: ${REST_URL_BASE}
      WEBSOCKET_URL: ${WEBSOCKET_URL}
      VERIFY_SSL: ${VERIFY_SSL:-true}
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
      ACTION_INTERVAL: ${ACTION_INTERVAL:-10000}
      CHANCE_CREATE_RFQ: ${CHANCE_CREATE_RFQ:-0.0}
      CHANCE_MODIFY_RFQ: ${CHANCE_MODIFY_RFQ:-0.0}
      CHANCE_CREATE_OFFER: ${CHANCE_CREATE_OFFER:-0.0}
      CHANCE_MODIFY_OFFER: ${CHANCE_MODIFY_OFFER:-0.0}
      CHANCE_ANSWER_OFFER: ${CHANCE_ANSWER_OFFER:-0.0}
      CHANCE_CREATE_COUNTER: ${CHANCE_CREATE_COUNTER:-0.0}
      CHANCE_MODIFY_COUNTER: ${CHANCE_MODIFY_COUNTER:-0.0}
      CHANCE_ANSWER_COUNTER: ${CHANCE_ANSWER_COUNTER:-0.0}
      CHANCE_MODIFY_RFQ_UPDATE: ${CHANCE_MODIFY_RFQ_UPDATE:-0.0}
      CHANCE_MODIFY_OFFER_UPDATE: ${CHANCE_MODIFY_OFFER_UPDATE:-0.0}
      CHANCE_MODIFY_COUNTER_UPDATE: ${CHANCE_MODIFY_COUNTER_UPDATE:-0.0}
      CHANCE_ANSWER_OFFER_ACCEPT: ${CHANCE_ANSWER_OFFER_ACCEPT:-0.0}
      CHANCE_ANSWER_COUNTER_ACCEPT: ${CHANCE_ANSWER_COUNTER_ACCEPT:-0.0}
      UPDATE_EXPIRING_ITEMS_ONLY: ${UPDATE_EXPIRING_ITEMS_ONLY:-true}
      EXPIRY_BUFFER: ${EXPIRY_BUFFER:-2}
      ASSET_FILTER: ${ASSET_FILTER:-}
      MARKET_WIDTH: ${MARKET_WIDTH:-0.002}
      ENABLED_ASSETS_FOR_OFFER: ${ENABLED_ASSETS_FOR_OFFER:-}
      SUPPORTED_SETTLEMENT_METHODS: ${SUPPORTED_SETTLEMENT_METHODS:-}
    volumes:
      - ${BUSYBOT_LOG_ROOT}/busybot:/var/log/busybot
